<?php

namespace DB\FactoryBundle\Entity;

/**
 * WarehouseStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
